### ISSUE TITLE
Configurar el directorio docs/ del repositorio como fuente para una página de GitHub

### ISSUE THREAD

**Issue by HeraclitoDeEfeso** [CISTAS/Tescucho2.0#23]
Para publicar una página desde el repositorio es necesario permisos de administrador.

Para configurar el directorio [`docs/`](https://github.com/CISTAS/Tescucho2.0/tree/master/docs) del repositorio como fuente para una página de GitHub, seguir las instrucciones en:

https://docs.github.com/es/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by Marouxet** [comment]
Hola Alejandro, 

Lo hago en esta semana. Gracias!

**Comment by Marouxet** [comment]
Hecho!
